name: Feature request
description: Suggest an idea for this project
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        **Search for existing issues first**
        Before suggesting a new feature, please use the issue search in the repository to check if a similar suggestion has already been made. This helps prevent duplicates and ensures your request gets proper attention.

        **Instructions**
        Create a title for your request and provide the required details in the sections below. Sections marked with a * are obligatory.
  - type: checkboxes
    attributes:
      label: Pre-Request Checklist
      description: Before submitting your feature request, please confirm the following
      options:
        - label: "I have checked Playnite's settings (e.g., in Settings -> Appearance) and confirmed that this change cannot be made there."
          required: true
        - label: "I have checked that this feature is not already available using the [ThemeModifier plugin](https://playnite.link/addons.html#playnite-thememodifier-plugin)."
          required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the suggested feature. Explain why it would be useful and how it enhances the project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Mockups
      description: If applicable, add screenshots or mockups to help visualize your idea, especially for UI changes.
    validations:
      required: false